---
- name: CentOS CrowdStrike    # 显示任务名
  hosts: all    # 定义主机
  #remote_user: centos    # 定义执行此playbook的用户
 
  tasks:    # 任务

  - name: 任务开始
    shell: echo "任务开始"

  - name: 下载并安装falcon-sensor包
    shell: sudo yum install -y https://miller-s3.s3.cn-north-1.amazonaws.com.cn/CrowdStrike/Linux/falcon-sensor-RHEL-CENTOS-ORACLE7.rpm

  - name: 设置cid
    shell: sudo /opt/CrowdStrike/falconctl -s --cid=74712C2BA207406C8D318FAD11099566-60

  - name: 启动falcon-sensor
    shell: sudo systemctl start falcon-sensor
    
  - name: 删除安装包
    shell: sudo rm -f falcon-sensor_Ubuntu_amd64.deb

  - name: 显示进程信息
    shell: ps -e | grep falcon-sensor