---
- name: CentOS CrowdStrike 安装    # 显示任务名
  hosts: all    # 定义主机
  #remote_user: centos    # 定义执行此playbook的用户
 
  tasks:    # 任务

  - name: CrowdStrike安装任务
    msg: "CrowdStrike安装任务开始"

  - name: 下载falcon-sensor包
    shell: shell: wget https://miller-s3.s3.cn-north-1.amazonaws.com.cn/CrowdStrike/Linux/falcon-sensor_Ubuntu_amd64.deb
    msg: "已安装成功"
    
  - name: 删除安装包
    shell: sudo rm -f falcon-sensor_Ubuntu_amd64.deb
    msg: "已成功删除"