---
- name: CentOS CrowdStrike
  hosts: all
 
  tasks:
 
  - name: CentOS CrowdStrike
    shell: echo "Hi! Tower is working."
    cd /
    wget https://miller-s3.s3.cn-north-1.amazonaws.com.cn/CrowdStrike/Linux/falcon-sensor_Ubuntu_amd64.deb