---
- name: Update Amazon Linux 2
  hosts: all
  become: true
  tasks:

  - name: apt update
    apt:
      update_cache: yes

  - name: apt upgrade
    apt:
      upgrade: yes
      autoremove: yes
      autoclean: yes